language: android
sudo: false
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
env:
  global:
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
